- hosts: kali
  tasks:
    # Install the core packages
    - import_tasks: roles/deploy_core.yml
    # apt installed tools
    - import_tasks: roles/deploy_packages.yml
    # Deploy custom scripts in the scripts directory
    - import_tasks: roles/deploy_scripts.yml 
    # Deploy wordlists
    - import_tasks: roles/deploy_wordlists.yml
    # Wallpaper
    - import_tasks: roles/change_wallpaper.yml
   
