- name: Check if /opt/qutwh-images/ exists
  stat:
    path: '/opt/qutwh-images/'
  register: qutwh_images

- name: Make /opt/qutwh-images/
  shell: mkdir /opt/qutwh-images/
  when: not qutwh_images.stat.exists

#################### Copy images
- name: Copying the wallpaper
  copy:
    src: '{{ item }}'
    dest: '/opt/qutwh-images/'
  with_fileglob:
    - 'imgs/QUTWH_full.jpg'

- name: Copying the login background
  copy:
    src: '{{ item }}'
    dest: '/opt/qutwh-images/'
  with_fileglob:
    - 'imgs/QUTWH_login.jpg'

- name: Copying the profile picture
  copy:
    src: '{{ item }}'
    dest: '/opt/qutwh-images/'
  with_fileglob:
    - 'imgs/QUTWH_profile.png'

#################### Set the images
- name: Set the wallpaper
  shell: cp /home/qutwh/QUTWH-Ansible-Playbook/custom-files/xfce4-desktop.xml /home/qutwh/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
  ignore_errors: true

- name: Save a copy of the original background symlink
  copy:
    src: /usr/share/desktop-base/kali-theme/login/background
    dest: /usr/share/desktop-base/kali-theme/login/background.bak

- name: Create new symlink to the new background
  shell: ln -sf /opt/qutwh-images/QUTWH_login.jpg /usr/share/desktop-base/kali-theme/login/background

- name: Add a login profile
  copy:
    src: /opt/qutwh-images/QUTWH_profile.png
    dest: /var/lib/AccountsService/icons/qutwh.png

- name: Set the login profile (1)
  copy:
    src: /home/qutwh/QUTWH-Ansible-Playbook/custom-files/qutwh
    dest: /var/lib/AccountsService/users/qutwh

- name: Set the login profile (2)
  copy:
    src: /home/qutwh/QUTWH-Ansible-Playbook/custom-files/lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf

      #  copy:
      #   src: /opt/qutwh-images/QUTWH_profile.png
      #   dest: /var/lib/AccountsService/icons/qutwh.png
      #  shell: echo -e '[User]\nIcon=/var/lib/AccountsService/icons/qutwh.png' | sudo tee -a /var/lib/AccountsService/users/qutwh

