- name: Check if /opt/qutwh-images/ exists
  stat:
    path: '/opt/qutwh-images/'
  register: qutwh_images

- name: Make /opt/qutwh-images/
  shell: mkdir /opt/qutwh-images/
  when: not qutwh_images.stat.exists

#################### Copy images
- name: Copying the wallpaper
  copy:
    src: '{{ item }}'
    dest: '/opt/qutwh-images/'
  with_fileglob:
    - 'imgs/QUTWH_full.jpg'

- name: Copying the login background
  copy:
    src: '{{ item }}'
    dest: '/opt/qutwh-images/'
  with_fileglob:
    - 'imgs/QUTWH_login.jpg'

- name: Copying the profile picture
  copy:
    src: '{{ item }}'
    dest: '/opt/qutwh-images/'
  with_fileglob:
    - 'imgs/QUTWH_profile.png'

#################### Set the images
- name: Check that wallpaper path exists
  stat: 
    path: '/backdrop/screen0/monitorVirtual1/workspace0/last-image'
  register: wallpaper_path

- name: Report if wallpaper path doesn't exist
  debug:
    msg: 'Unable to find /backdrop/screen0/monitorVirtual1/workspace0/last-image please reboot and try again'
  when: not wallpaper_path.stat.exists

- name: Set the wallpaper
  shell: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorVirtual1/workspace0/last-image -s /opt/qutwh-images/QUTWH_full.png
  when: wallpaper_path.stat.exists

- name: Save a copy of the original background symlink
  copy:
    src: /usr/share/desktop-base/kali-theme/login/background
    dest: /usr/share/desktop-base/kali-theme/login/background.bak
- name: Create new symlink to the new background
  shell: ln -sf /opt/qutwh-images/QUTWH_login.jpg /usr/share/desktop-base/kali-theme/login/background

- name: Set the login profile
  copy:
    src: /opt/qutwh-images/QUTWH_profile.png
    dest: /home/qutwh/.face
      #  copy:
      #   src: /opt/qutwh-images/QUTWH_profile.png
      #   dest: /var/lib/AccountsService/icons/qutwh.png
      #  shell: echo -e '[User]\nIcon=/var/lib/AccountsService/icons/qutwh.png' | sudo tee -a /var/lib/AccountsService/users/qutwh

