#################### Copy executables
- name: Copying the picture
  copy:
    src: "{{ item }}"
    dest: '/root/Pictures'
  with_fileglob:
    - "imgs/QUTWH_full.jpg"

#################### Set the picture
- name: Set the background
  shell: gsettings set org.gnome.desktop.background picture-uri file:///root/Pictures/QUTWH_full.png
