#################### Copy images
- name: Copying the wallpaper
  copy:
    src: '{{ item }}'
    dest: '/root/Pictures'
  with_fileglob:
    - 'imgs/QUTWH_full.jpg'
- name: Copying the login background
  copy:
    src: '{{ item }}'
    dest: '/root/Pictures'
  with_fileglob:
    - 'imgs/QUTWH_login.jpg'
- name: Copying the profile picture
  copy:
    src: '{{ item }}'
    dest: '/root/Pictures'
  with_fileglob:
    - 'imgs/QUTWH_profile.png'
#################### Set the images
- name: Set the wallpaper
  shell: mv /usr/share/desktop-base/kali-theme/wallpaper/contents/images/3840x2160.png /usr/share/desktop-base/kali-theme/wallpaper/contents/images/3840x2160.bak
  copy:
    src: /root/Pictures/QUTWH_full.jpg
    dest: /usr/share/desktop-base/kali-theme/wallpaper/contents/images/3840x2160.png
- name: Set the login background and save a copy of the original
  copy:
    src: /usr/share/desktop-base/kali-theme/login/background
    dest: /usr/share/desktop-base/kali-theme/login/background.bak
  shell: ln -s /root/Pictures/QUTWH_login.jpg /usr/share/desktop-base/kali-theme/login/background
- name: Set the login profile
  shell: echo -E 'default-user-image=/root/Pictures/QUTWH_profile.png' >> /ect/lightdm/lightdm-gtk-greeter.conf

#shell: gsettings set org.gnome.desktop.background picture-uri 'file:///root/Pictures/QUTWH_full.jpg'; gsettings set org.gnome.desktop.background picture-uri-dark 'file:///root/Pictures/QUTWH_full.jpg'
